//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string cmd_AddNew {
            get {
                return ResourceManager.GetString("cmd_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string cmd_Back {
            get {
                return ResourceManager.GetString("cmd_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string cmd_Cancel {
            get {
                return ResourceManager.GetString("cmd_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string cmd_Delete {
            get {
                return ResourceManager.GetString("cmd_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string cmd_Detail {
            get {
                return ResourceManager.GetString("cmd_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đỗi.
        /// </summary>
        internal static string cmd_Edit {
            get {
                return ResourceManager.GetString("cmd_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string cmd_Insert {
            get {
                return ResourceManager.GetString("cmd_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới &amp; Tiếp tục.
        /// </summary>
        internal static string cmd_InsertAndContinue {
            get {
                return ResourceManager.GetString("cmd_InsertAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        internal static string cmd_List {
            get {
                return ResourceManager.GetString("cmd_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string cmd_Save {
            get {
                return ResourceManager.GetString("cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu &amp; Tiếp tục.
        /// </summary>
        internal static string cmd_SaveAndContinue {
            get {
                return ResourceManager.GetString("cmd_SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string cmd_Update {
            get {
                return ResourceManager.GetString("cmd_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa dữ liệu được chọn?.
        /// </summary>
        internal static string mgs_ConfirmDelete {
            get {
                return ResourceManager.GetString("mgs_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string mgs_DeleteSuccess {
            get {
                return ResourceManager.GetString("mgs_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        internal static string mgs_InsertSuccess {
            get {
                return ResourceManager.GetString("mgs_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu.
        /// </summary>
        internal static string mgs_NoData {
            get {
                return ResourceManager.GetString("mgs_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        internal static string mgs_UpdateSuccess {
            get {
                return ResourceManager.GetString("mgs_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string nav_Register {
            get {
                return ResourceManager.GetString("nav_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hinh.
        /// </summary>
        internal static string nav_Setting {
            get {
                return ResourceManager.GetString("nav_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        internal static string nav_User {
            get {
                return ResourceManager.GetString("nav_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string nav_Wiget {
            get {
                return ResourceManager.GetString("nav_Wiget", resourceCulture);
            }
        }
    }
}
